_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.5
            "6": 4.40.0
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 256
device:
    value: cuda
epsilon_decay:
    value: 1000
epsilon_end:
    value: 0.05
epsilon_start:
    value: 0.9
fake_structure_prediction:
    value: true
gamma:
    value: 0.99
lr:
    value: 0.0001
max_buffer_size:
    value: 1000000
max_episode_length:
    value: 200
n_epochs:
    value: 10000
project_name:
    value: qres_stability
save_interval:
    value: 100
sequence_length:
    value: 30
tau:
    value: 0.005
train_iterations_per_batch:
    value: 10
wandb_enabled:
    value: true
